language: go
go:
- '1.8'
sudo: false

before_install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -

install:
  make vendor

script:
- make build
- make darwin
- make freebsd

before_deploy:
- mkdir -p bin_release
- CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/gonaomi_linux-amd64
- CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/gonaomi_darwin-amd64
- CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -a -ldflags "-extldflags '-static' -X main.AppVersion=$TRAVIS_TAG" -o bin_release/gonaomi_freebsd-amd64

deploy:
  provider: releases
  api_key:
    secure: LzdhKMDimTP+y0JtUt7N8i6Q7muweEvxUwqUQNkzsOv9fJ39qLxhopqQ3jSYgedfsX1e29CIDgLtXuJK16phUlgzhLogPNB+SYolQ0hYORCoi4ptJBx3BMPp8iA6ma6d+a0eL927vunTByabOwqhqvMVH4mnNTllRq3Meef8Ihg5C3GhNzfkgQFUCVysxe9fSRRjb3zim56Oi/rdt6pU66KqyAcAdkY8fLeqwq1/prVK2OBY4YKDtPxp68hgAMkcNsbRpyc0NQP69dpCsDEeS7afT2gCEiJIP9BtPAuKgyasL0Uxh0qNW0jAwj8FHb4WzHIkeDz+WuU/O5KfA3iw3MNRewLahnmHvFGi6f2xvd9NyDX6j31PdKcegXF1Okq9OgqJbR93Q+XV+zC+86owtsFPL4PogkJPSMhmwExB47tmV7B5QUr5lY07K9T+rwT1ITRghY+wrv8pDY6M+tKyTqOxjO5JCLE0t796W39YTtn6RcbrG2t7iXSZDZVlMl2IYbAWDbf8ISKsIADWJTbjcZaPJHKWSKTlG7tcF+BT5P4/XCCSGMQ1fXZymNpEBXPPyT2pzrZK+3ebaNHr2RrJze7SprUaVT/2x8jARbKCl8WvbS//16pifWt+M/9fjcvEQZA/PLHoPZdYRHrzUcw8sbayYhfan2GgXFlHxcT3uKU=
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
go: 1.8
